name: cmake-docker
# - Verifies a plain (non-nix) cmake build works inside docker-xo-builder.
# Links:
# - org-howto/articles/2026/06/forgejo/docker-container-registry.org
# - xo-umbrella2/pkgs/docker-xo-builder.nix

on:
  push:
    branches: [main]

jobs:
  cmake-build:
    runs-on: xo-builder
    env:
      PREFIX: ${{github.workspace}}/local
    steps:
      - name: set PATH
        run: |
          echo "$PREFIX/bin" >> $GITHUB_PATH

      - name: pkgconfig
        run: |
          # list packages known to pkg-config
          pkg-config --list-all

      - name: dirs
        run: |
          tree -L 1 /include
          ls /lib

      - name: checkout
        run: |
          echo PATH=${PATH}
          git clone --quiet --depth=1 $GITHUB_SERVER_URL/roland/xo-umbrella2.git .
          mkdir -p "$PREFIX"

      - name: bootstrap xo-cmake
        run: |
          echo "::group::xo-cmake configure"
          cmake -S xo-cmake -B .build/xo-cmake -DCMAKE_INSTALL_PREFIX=$PREFIX
          echo "::endgroup::"

          echo "::group::xo-cmake build (no-op)"
          cmake --build .build/xo-cmake
          echo "::endgroup::"

          echo "::group::xo-cmake install"
          cmake --install .build/xo-cmake
          echo "::endgroup::"

      - name: build xo-subsys
        run: |
          echo "::group::xo-subsys configure"
          xo-build --configure --with-utests --with-examples xo-subsys
          echo "::endgroup::"

          echo "::group::xo-subsys build"
          xo-build --build xo-subsys
          echo "::endgroup::"

          echo "::group::xo-subsys utest"
          ctest --test-dir xo-subsys/.build
          echo "::endgroup::"

          echo "::group::xo-subsys install"
          xo-build --install xo-subsys
          echo "::endgroup::"

      - name: build xo-timeutil
        run: |
          echo "::group::xo-timeutil configure"
          xo-build --configure --with-utests --with-examples xo-timeutil
          echo "::endgroup::"

          echo "::group::xo-timeutil build"
          xo-build --build xo-timeutil
          echo "::endgroup::"

          echo "::group::xo-timeutil utest"
          ctest --test-dir xo-timeutil/.build
          echo "::endgroup::"

          echo "::group::xo-timeutil install"
          xo-build --install xo-timeutil
          echo "::endgroup::"

      - name: build xo-indentlog
        run: |
          echo "::group::xo-indentlog configure"
          xo-build --configure --with-utests --with-examples xo-indentlog
          echo "::endgroup::"

          echo "::group::xo-indentlog build"
          xo-build --build xo-indentlog
          echo "::endgroup::"

          echo "::group::xo-indentlog utest"
          ctest --test-dir xo-indentlog/.build
          echo "::endgroup::"

          echo "::group::xo-indentlog install"
          xo-build --install xo-indentlog
          echo "::endgroup::"

      - name: build xo-flatstring
        run: |
          echo "::group::xo-flatstring configure"
          xo-build --configure --with-utests --with-examples xo-flatstring
          echo "::endgroup::"

          echo "::group::xo-flatstring build"
          xo-build --build xo-flatstring
          echo "::endgroup::"

          echo "::group::xo-flatstring utest"
          ctest --test-dir xo-flatstring/.build
          echo "::endgroup::"

          echo "::group::xo-flatstring install"
          xo-build --install xo-flatstring
          echo "::endgroup::"

      - name: build xo-randomgen
        run: |
          echo "::group::xo-randomgen configure"
          xo-build --configure --with-utests --with-examples xo-randomgen
          echo "::endgroup::"

          echo "::group::xo-randomgen build"
          xo-build --build xo-randomgen
          echo "::endgroup::"

          echo "::group::xo-randomgen utest"
          ctest --test-dir xo-randomgen/.build
          echo "::endgroup::"

          echo "::group::xo-randomgen install"
          xo-build --install xo-randomgen
          echo "::endgroup::"

      - name: build xo-reflectutil
        run: |
          echo "::group::xo-reflectutil configure"
          xo-build --configure --with-utests --with-examples xo-reflectutil
          echo "::endgroup::"

          echo "::group::xo-reflectutil build"
          xo-build --build xo-reflectutil
          echo "::endgroup::"

          echo "::group::xo-reflectutil utest"
          ctest --test-dir xo-reflectutil/.build
          echo "::endgroup::"

          echo "::group::xo-reflectutil install"
          xo-build --install xo-reflectutil
          echo "::endgroup::"

      - name: build xo-arena
        run: |
          echo "::group::xo-arena configure"
          xo-build --configure --with-utests --with-examples xo-arena
          echo "::endgroup::"

          echo "::group::xo-arena build"
          xo-build --build xo-arena
          echo "::endgroup::"

          echo "::group::xo-arena utest"
          ctest --test-dir xo-arena/.build
          echo "::endgroup::"

          echo "::group::xo-arena install"
          xo-build --install xo-arena
          echo "::endgroup::"

      - name: build xo-testutil
        run: |
          echo "::group::xo-testutil configure"
          xo-build --configure --with-utests --with-examples xo-testutil
          echo "::endgroup::"

          echo "::group::xo-testutil build"
          xo-build --build xo-testutil
          echo "::endgroup::"

          echo "::group::xo-testutil utest"
          ctest --test-dir xo-testutil/.build
          echo "::endgroup::"

          echo "::group::xo-testutil install"
          xo-build --install xo-testutil
          echo "::endgroup::"

      - name: build xo-indentlog2
        run: |
          echo "::group::xo-indentlog2 configure"
          xo-build --configure --with-utests --with-examples xo-indentlog2
          echo "::endgroup::"

          echo "::group::xo-indentlog2 build"
          xo-build --build xo-indentlog2
          echo "::endgroup::"

          echo "::group::xo-indentlog2 utest"
          ctest --test-dir xo-indentlog2/.build
          echo "::endgroup::"

          echo "::group::xo-indentlog2 install"
          xo-build --install xo-indentlog2
          echo "::endgroup::"

      - name: build xo-facet
        run: |
          echo "::group::xo-facet configure"
          xo-build --configure --with-utests --with-examples xo-facet
          echo "::endgroup::"

          echo "::group::xo-facet build"
          xo-build --build xo-facet
          echo "::endgroup::"

          echo "::group::xo-facet utest"
          ctest --test-dir xo-facet/.build
          echo "::endgroup::"

          echo "::group::xo-facet install"
          xo-build --install xo-facet
          echo "::endgroup::"

      - name: build xo-printable2
        run: |
          echo "::group::xo-printable2 configure"
          xo-build --configure --with-utests --with-examples xo-printable2
          echo "::endgroup::"

          echo "::group::xo-printable2 build"
          xo-build --build xo-printable2
          echo "::endgroup::"

          echo "::group::xo-printable2 utest"
          ctest --test-dir xo-printable2/.build
          echo "::endgroup::"

          echo "::group::xo-printable2 install"
          xo-build --install xo-printable2
          echo "::endgroup::"

      - name: build xo-alloc2
        run: |
          echo "::group::xo-alloc2 configure"
          xo-build --configure --with-utests --with-examples xo-alloc2
          echo "::endgroup::"

          echo "::group::xo-alloc2 build"
          xo-build --build xo-alloc2
          echo "::endgroup::"

          echo "::group::xo-alloc2 utest"
          ctest --test-dir xo-alloc2/.build
          echo "::endgroup::"

          echo "::group::xo-alloc2 install"
          xo-build --install xo-alloc2
          echo "::endgroup::"

      - name: build xo-refcnt
        run: |
          echo "::group::xo-refcnt configure"
          xo-build --configure --with-utests --with-examples xo-refcnt
          echo "::endgroup::"

          echo "::group::xo-refcnt build"
          xo-build --build xo-refcnt
          echo "::endgroup::"

          echo "::group::xo-refcnt utest"
          ctest --test-dir xo-refcnt/.build
          echo "::endgroup::"

          echo "::group::xo-refcnt install"
          xo-build --install xo-refcnt
          echo "::endgroup::"

      - name: build xo-pyutil
        run: |
          echo "::group::xo-pyutil configure"
          xo-build --configure --with-utests --with-examples xo-pyutil
          echo "::endgroup::"

          echo "::group::xo-pyutil build"
          xo-build --build xo-pyutil
          echo "::endgroup::"

          echo "::group::xo-pyutil utest"
          ctest --test-dir xo-pyutil/.build
          echo "::endgroup::"

          echo "::group::xo-pyutil install"
          xo-build --install xo-pyutil
          echo "::endgroup::"

      - name: build xo-reflect
        run: |
          echo "::group::xo-reflect configure"
          xo-build --configure --with-utests --with-examples xo-reflect
          echo "::endgroup::"

          echo "::group::xo-reflect build"
          xo-build --build xo-reflect
          echo "::endgroup::"

          echo "::group::xo-reflect utest"
          ctest --test-dir xo-reflect/.build
          echo "::endgroup::"

          echo "::group::xo-reflect install"
          xo-build --install xo-reflect
          echo "::endgroup::"

      - name: build xo-pyreflect
        run: |
          echo "::group::xo-pyreflect configure"
          xo-build --configure --with-utests --with-examples xo-pyreflect
          echo "::endgroup::"

          echo "::group::xo-pyreflect build"
          xo-build --build xo-pyreflect
          echo "::endgroup::"

          echo "::group::xo-pyreflect utest"
          ctest --test-dir xo-pyreflect/.build
          echo "::endgroup::"

          echo "::group::xo-pyreflect install"
          xo-build --install xo-pyreflect
          echo "::endgroup::"

      - name: build xo-stringtable2
        run: |
          echo "::group::xo-stringtable2 configure"
          xo-build --configure --with-utests --with-examples xo-stringtable2
          echo "::endgroup::"

          echo "::group::xo-stringtable2 build"
          xo-build --build xo-stringtable2
          echo "::endgroup::"

          echo "::group::xo-stringtable2 utest"
          ctest --test-dir xo-stringtable2/.build
          echo "::endgroup::"

          echo "::group::xo-stringtable2 install"
          xo-build --install xo-stringtable2
          echo "::endgroup::"

      - name: build xo-object2
        run: |
          echo "::group::xo-object2 configure"
          xo-build --configure --with-utests --with-examples xo-object2
          echo "::endgroup::"

          echo "::group::xo-object2 build"
          xo-build --build xo-object2
          echo "::endgroup::"

          echo "::group::xo-object2 utest"
          ctest --test-dir xo-object2/.build
          echo "::endgroup::"

          echo "::group::xo-object2 install"
          xo-build --install xo-object2
          echo "::endgroup::"

      - name: print install path
        run: |
          tree ${{github.workspace}}/local
