name: CI
on:
  push:
    branches: [main]

jobs:
  smoke-test:
    runs-on: host
    steps:

      - name: debug env
        run:
          env | sort

      - name: Setup PATH
        run: |
          echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH
          echo "/var/lib/forgejo-runner/.nix-profile/bin" >> $GITHUB_PATH

      - name: Check PATH
        run:
          echo $PATH

      - name: Check cwd
        run:
          pwd

      - name: Check nix version
        run:
          echo $(nix --version)

      - name: nix store ping
        run:
          nix store info

      - name: checkout
        uses:
          actions/checkout@v4

      - name: build xo-cmake
        run:
          nix-build ci.nix -A xo-cmake
