name: CI
on:
  push:
    branches: [main]

jobs:
  smoke-test:
    runs-on: host
    steps:

      - name: debug env
        run:
          env | sort

      - name: Setup PATH
        run: |
          echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH
          echo "/var/lib/forgejo-runner/.nix-profile/bin" >> $GITHUB_PATH

      - name: Check PATH
        run:
          echo $PATH

      - name: Check cwd
        run:
          pwd

      - name: Check nix version
        run:
          echo $(nix --version)

      - name: nix store ping
        run:
          nix store info

      - name: checkout
        run: |
          # 1. actions/checkout@v4 stumbles b/c install is at conybeare.us/git
          #    checkout manually instead.
          # 2. could clone from /var/lib/forgejo/gitea-repositories/roland/xo-umbrella2.git
          # 3. instead rely on $GITHUB_SERVER_URL

          git clone --quiet --depth=1 $GITHUB_SERVER_URL/roland/xo-umbrella2.git .

      - name: build xo-cmake
        run:
          nix-build ci.nix -A xo-cmake

      - name: build xo-indentlog
        run:
          nix-build ci.nix -A xo-indentlog
