name: CI
on:
  push:
    branches: [main]

jobs:
  smoke-test:
    runs-on: host
    steps:

      - name: debug env
        run:
          env | sort

      - name: Setup PATH
        run: |
          echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH
          echo "/var/lib/forgejo-runner/.nix-profile/bin" >> $GITHUB_PATH

      - name: Check PATH
        run:
          echo $PATH

      - name: Check cwd
        run:
          pwd

      - name: Check nix version
        run:
          echo $(nix --version)

      - name: nix store ping
        run:
          nix store info

      - name: checkout
        run: |
          # 1. actions/checkout@v4 stumbles b/c install is at conybeare.us/git
          #    checkout manually instead.
          # 2. could clone from /var/lib/forgejo/gitea-repositories/roland/xo-umbrella2.git
          # 3. instead rely on $GITHUB_SERVER_URL

          git clone --quiet --depth=1 $GITHUB_SERVER_URL/roland/xo-umbrella2.git .

      - name: build xo-cmake
        run: |
          echo nix-build ci.nix -A xo-cmake
          nix-build ci.nix -A xo-cmake
          ls -l ./result

      - name: build xo-indentlog
        run: |
          echo nix-build ci.nix -A xo-indentlog
          nix-build ci.nix -A xo-indentlog
          ls -l ./result

      - name: build xo-subsys
        run: |
          echo nix-build ci.nix -A xo-subsys
          nix-build ci.nix -A xo-subsys
          ls -l ./result

      - name: build xo-flatstring
        run: |
          echo nix-build ci.nix -A xo-flatstring
          nix-build ci.nix -A xo-flatstring
          ls -l ./result

      - name: build xo-randomgen
        run: |
          echo nix-build ci.nix -A xo-randomgen
          nix-build ci.nix -A xo-randomgen
          ls -l ./result

      - name: build xo-reflectutil
        run: |
          echo nix-build ci.nix -A xo-reflectutil
          nix-build ci.nix -A xo-reflectutil
          ls -l ./result

      - name: build xo-arena
        run: |
          echo nix-build ci.nix -A xo-arena
          nix-build ci.nix -A xo-arena
          ls -l ./result

      - name: build xo-facet
        run: |
          echo nix-build ci.nix -A xo-type
          nix-build ci.nix -A xo-facet
          ls -l ./result

      - name: build xo-printable2
        run: |
          echo nix-build ci.nix -A xo-printable2
          nix-build ci.nix -A xo-printable2
          ls -l ./result

      - name: build xo-testutil
        run: |
          echo nix-build ci.nix -A xo-testutil
          nix-build ci.nix -A xo-testutil
          ls -l ./result

      - name: build xo-alloc2
        run: |
          echo nix-build ci.nix -A xo-alloc2
          nix-build ci.nix -A xo-alloc2
          ls -l ./result

      - name: build xo-refcnt
        run: |
          echo nix-build ci.nix -A xo-refcnt
          nix-build ci.nix -A xo-refcnt
          ls -l ./result

      - name: build xo-pyutil
        run: |
          echo nix-build ci.nix -A xo-pyutil
          nix-build ci.nix -A xo-pyutil
          ls -l ./result

      - name: build xo-reflect
        run: |
          echo nix-build ci.nix -A xo-reflect
          nix-build ci.nix -A xo-reflect
          ls -l ./result

      - name: build xo-pyreflect
        run: |
          echo nix-build ci.nix -A xo-pyreflect
          nix-build ci.nix -A xo-pyreflect
          ls -l ./result

      - name: build xo-stringtable2
        run: |
          echo nix-build ci.nix -A xo-stringtable2
          nix-build ci.nix -A xo-stringtable2
          ls -l ./result

      - name: build xo-object2
        run: |
          echo nix-build ci.nix -A xo-object2
          nix-build ci.nix -A xo-object2
          ls -l ./result

      - name: build xo-gc
        run: |
          echo nix-build ci.nix -A xo-gc
          nix-build ci.nix -A xo-gc
          ls -l ./result

      - name: build xo-type
        run: |
          echo nix-build ci.nix -A xo-type
          nix-build ci.nix -A xo-type
          ls -l ./result

      - name: build xo-procedure2
        run: |
          echo nix-build ci.nix -A xo-procedure2
          nix-build ci.nix -A xo-procedure2
          ls -l ./result

      - name: build xo-numeric
        run: |
          echo nix-build ci.nix -A xo-numeric
          nix-build ci.nix -A xo-numeric
          ls -l ./result

      - name: build xo-tokenizer2
        run: |
          echo nix-build ci.nix -A xo-tokenizer2
          nix-build ci.nix -A xo-tokenizer2
          ls -l ./result

      - name: build xo-expression2
        run: |
          echo nix-build ci.nix -A xo-expression2
          nix-build ci.nix -A xo-expression2
          ls -l ./result

      - name: build xo-reader2
        run: |
          echo nix-build ci.nix -A xo-reader2
          nix-build ci.nix -A xo-reader2
          ls -l ./result

      - name: build xo-interpreter2
        run: |
          echo nix-build ci.nix -A xo-interpreter2
          nix-build ci.nix -A xo-interpreter2
          ls -l ./result

      - name: build xo-allocutil
        run: |
          echo nix-build ci.nix -A xo-allocutil
          nix-build ci.nix -A xo-allocutil
          ls -l ./result

      - name: build xo-alloc
        run: |
          echo nix-build ci.nix -A xo-alloc
          nix-build ci.nix -A xo-alloc
          ls -l ./result

      - name: build xo-ratio
        run: |
          echo nix-build ci.nix -A xo-ratio
          nix-build ci.nix -A xo-ratio
          ls -l ./result

      - name: build xo-unit
        run: |
          echo nix-build ci.nix -A xo-unit
          nix-build ci.nix -A xo-unit
          ls -l ./result

      - name: build xo-pyunit
        run: |
          echo nix-build ci.nix -A xo-pyunit
          nix-build ci.nix -A xo-pyunit
          ls -l ./result

      - name: build xo-pyunit
        run: |
          echo nix-build ci.nix -A xo-pyunit
          nix-build ci.nix -A xo-pyunit
          ls -l ./result

      - name: build xo-callback
        run: |
          echo nix-build ci.nix -A xo-callback
          nix-build ci.nix -A xo-callback
          ls -l ./result

      - name: build xo-object
        run: |
          echo nix-build ci.nix -A xo-object
          nix-build ci.nix -A xo-object
          ls -l ./result

      - name: build xo-ordinaltree
        run: |
          echo nix-build ci.nix -A xo-ordinaltree
          nix-build ci.nix -A xo-ordinaltree
          ls -l ./result

      - name: build xo-expression
        run: |
          echo nix-build ci.nix -A xo-expression
          nix-build ci.nix -A xo-expression
          ls -l ./result

      - name: build xo-pyexpression
        run: |
          echo nix-build ci.nix -A xo-pyexpression
          nix-build ci.nix -A xo-pyexpression
          ls -l ./result

      - name: build xo-tokenizer
        run: |
          echo nix-build ci.nix -A xo-tokenizer
          nix-build ci.nix -A xo-tokenizer
          ls -l ./result

      - name: build xo-reader
        run: |
          echo nix-build ci.nix -A xo-reader
          nix-build ci.nix -A xo-reader
          ls -l ./result

      - name: build xo-jit
        run: |
          echo nix-build ci.nix -A xo-jit
          nix-build ci.nix -A xo-jit
          ls -l ./result

      - name: build xo-pyjit
        run: |
          echo nix-build ci.nix -A xo-pyjit
          nix-build ci.nix -A xo-pyjit
          ls -l ./result
