name: build on ubuntu base platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize CMake build type here
  BUILD_TYPE: Release

jobs:
  build:
    # This build won't be entirely reproducible, given ubuntu changes on github runners may
    # introduce regressions.
    #
    runs-on: ubuntu-latest

    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: bootstrap xo-cmake
        run: |
          PREFIX=${{github.workspace}}/local
          mkdir -p ${PREFIX}
          echo "::group::xo-cmake configure"
          cmake -B .build0 -S xo-cmake -DCMAKE_INSTALL_PREFIX=${PREFIX}
          echo "::group::xo-cmake build"
          cmake --build .build0
          echo "::group::xo-cmake install"
          cmake --install .build0

      - name: build xo subprojects
        run: |
          echo "::group::xo configure"
          cmake -B .build -B . -DCMAKE_INSTALL_PREFIX=${PREFIX}
          echo "::group::xo build"
          cmake --build .build
          echo "::gorup::xo install"
          cmake --install .build

      - name: print install path
        run: |
          tree ${{github.workspace}}/local
